New structure of the directories

diff --git a/makeDeb b/makeDeb
--- a/makeDeb
+++ b/makeDeb
@@ -1,32 +1,65 @@
 #!/bin/bash
 
-NAME='flacon'
+# BEGIN_COMMON_COPYRIGHT_HEADER
+# (c)LGPL2+
+#
+#
+# Copyright: 2014 Alexander Sokoloff
+# Authors:
+#   Alexander Sokoloff <sokoloff.a@gmail.com>
+#
+# This program or library is free software; you can redistribute it
+# and/or modify it under the terms of the GNU Lesser General Public
+# License as published by the Free Software Foundation; either
+# version 2.1 of the License, or (at your option) any later version.
+#
+# This library is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# Lesser General Public License for more details.
+
+# You should have received a copy of the GNU Lesser General
+# Public License along with this library; if not, write to the
+# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
+# Boston, MA 02110-1301 USA
+#
+# END_COMMON_COPYRIGHT_HEADER
+
+SCRIPT_VERSION="0.6.0"
+
+
+function version {
+    echo "makeDeb $SCRIPT_VERSION"
+    exit
+}
 
 function help {
   cat << HELP_TEXT
-Usage: makeDeb.sh [options] <path-to-source>
-   or  makeDeb.sh [options] <path-to-source-tar-file>
+Usage: makeDeb.sh [options] <spec-file>
 
 Options
   -h|--help             display this message
   -o|--outdirt=DIR      write result to DIR, home directory by default
-  -r|--release=RELEASE  release name (sid, squeeze, testing, maveric, natty etc.), autodetect if ommited
-  -d|--distrib=DISTRIB  distib type (Debian or Ubuntu), autodetect if ommited
-  --ver=VERSION         package version
-  -S|--sign             sign a result files
-  -s|--source           build a source package, if omitted build a binary package
-  --debug               debug mode, not build package - only create debian directory
-  --debdir              path to debian directory, if omitted used distr/deb/debian from the source dir or tar file.
+  -V|--version          Print program version
 HELP_TEXT
 }
 
-
+COLOR_NORM='\e[0m'
+COLOR_BLUE='\e[1;37;44m'
+COLOR_GREEN='\e[0;30;42m'
 
 VARIABLES=""
 
+
+function error()
+{
+    echo $1 >&2
+    exit 1
+}
+
 function debug
 {
-    [ -n "$DEBUG" ] && echo $@ >&2
+    [ -z "${DEBUG}" ] && echo "$@" >&2
 }
 
 function setVariable
@@ -69,7 +102,7 @@ function checkIf
             ;;
 
         *)
-            val=`getVariable ${name}`
+            val=`getVariable ${PROGRAM}`
             ;;
     esac
 
@@ -99,9 +132,10 @@ function nextToken
 
             *)
                 echo "$line" | sed            \
-                    -e"s/%NAME%/${NAME}/g"    \
-                    -e"s/%VERSION%/${VER}/g"  \
+                    -e"s/%NAME%/${PROGRAM}/g"    \
+                    -e"s/%VERSION%/${VERSION}/g"  \
                     -e"s/%RELEASE%/${RELEASE}/g" \
+                    -e"s/%RELEASENUM%/${RELEASENUM}/g" \
                     -e"s/%DISTRIB%/${DISTRIB}/g" \
                     -e"s/%DATE%/${DATE}/g" \
                     -e"s/%DEBEMAIL%/${DEBEMAIL}/g" \
@@ -197,10 +231,7 @@ function prepareFile
 }
 
 
-TYPE='-b'
-SIGN='-uc -us'
-SRC="../.."
-DEB_DIR=""
+SPEC=""
 
 while [ $# -gt 0 ]; do
   case $1 in
@@ -208,121 +239,68 @@ while [ $# -gt 0 ]; do
         help
         exit
       ;;
-
+    -V|--version)
+        version
+        exit
+      ;;  
     -o|--outdir)
         OUT_DIR=$2;
         shift 2
       ;;
 
-    -r|--release)
-        RELEASE=$2
-        shift 2
-      ;;
-
-    -d|--distrib)
-        DISTRIB=$2
-        shift 2
-      ;;
-
-    --ver)
-        VER=$2
-        shift 2
-      ;;
-
-    -s|--source)
-        TYPE='-S'
-        shift
-      ;;
-
-    -S|--sign)
-        SIGN=''
-        shift
-      ;;
-
-    --debug)
-        DEBUG=1
-        shift
-      ;;
-
-    --debdir)
-        DEB_DIR=$2
-        shift 2
-      ;;
-
-    --)
-        shift
-        break
-      ;;
 
     *)
-        SRC=$1
+        SPEC=$1
         shift
       ;;
 
   esac
 done
 
+# Default values --------------------------------
+DEB_DIR='debian'
+TYPE="source"
+SIGN=yes
+OUT_DIR="./OUT"
+RELEASENUM=1
 
-if [ -z "${SRC}" ]; then
-    echo "missing path-to-source operand" >&2
-    help
-    exit 2
-fi
-
-SRC=`readlink -m ${SRC}`
-
-if [ -d "${SRC}" ]; then
-  SRC_TYPE="DIR"
+# Read spec file  -------------------------------
+if [ -z "${SPEC}" ]; then
+    ls *.spec 2>/dev/null  || error "I can't find .spec file"
+    . *.spec 2>/dev/null   || error "I can't load .spec file"
 else
-  SRC_TYPE="FILE"
-fi
-
-if [ ${SRC_TYPE} = "DIR" ]; then
-    if [ ! -f ${SRC}/CMakeLists.txt ]; then
-        echo "The source directory \"${SRC}\" does not appear to contain CMakeLists.txt."
-        echo "Please run this script from root source dir ... as last argument"
-        exit 2
-    fi
-fi
-
-if [ -z "${RELEASE}" ]; then
-    RELEASE=`awk -F"=" '/DISTRIB_CODENAME=/ {print($2)}' /etc/lsb?release`
-fi
-
-if [ -z "${RELEASE}" ]; then
-    echo "missing release option"
-    help
-    exit 2
+    ls ${SPEC} 2>/dev/null || error "I can't find .spec file"
+    . ${SPEC} 2>/dev/null  || error "I can't load .spec file"
 fi
 
 
-if [ -z "${DISTRIB}" ]; then
-    DISTRIB=`awk -F"=" '/DISTRIB_ID=/ {print($2)}' /etc/lsb?release`
-fi
+# Checks ----------------------------------------
+DEB_DIR_PATH=$(realpath ${DEB_DIR})
+[ -d "${DEB_DIR_PATH}"  ] || error "I can't find debian directory (${DEB_DIR_PATH})!"
 
-if [ -z "${DISTRIB}" ]; then
-    echo "missing distrib option"
-    help
-    exit 2
-fi
+[ "${SIGN}" = "no" ] && sign_arg="-uc -us"
 
-if [ -z "$VER" ]; then
-    if [ ${SRC_TYPE} = "DIR" ]; then
-      MAJOR_VER=$(awk -F'[() ]' '/set\s*\(MAJOR_VERSION / {print($3)}' ${SRC}/CMakeLists.txt)
-      MINOR_VER=$(awk -F'[() ]' '/set\s*\(MINOR_VERSION / {print($3)}' ${SRC}/CMakeLists.txt)
-      PATCH_VER=$(awk -F'[() ]' '/set\s*\(PATCH_VERSION / {print($3)}' ${SRC}/CMakeLists.txt)
-    else
-      MAJOR_VER=$(echo "${SRC}" | awk -F '[-_]' '{print($2)}' | awk -F '.' '{print($1)}')
-      MINOR_VER=$(echo "${SRC}" | awk -F '[-_]' '{print($2)}' | awk -F '.' '{print($2)}')
-      PATCH_VER=$(echo "${SRC}" | awk -F '[-_]' '{print($2)}' | awk -F '.' '{print($3)}')
-    fi
 
-    VER="${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}"
-fi
+case ${TYPE} in
+    b*)
+        type_arg=""
+        ;;
 
-if [ -z "$OUT_DIR" ]; then
-    OUT_DIR="${HOME}/${NAME}_${VER}_deb"
-fi
+    s*)
+        type_arg="-S"
+        ;;
+
+    d*)
+        type_arg=""
+        ;;
+esac
+
+
+
+TAR_FILE="${PROGRAM}-${VERSION}.tar.gz"
+TAR_FILE_PATH=$(realpath ${TAR_FILE})
+[ -f "${TAR_FILE_PATH}" ] || error "I'cant find tar file '${TAR_FILE_PATH}'!"
+
 
 if [ -z "$DEBEMAIL" ]; then
   DEBEMAIL=${EMAIL}
@@ -332,65 +310,73 @@ if [ -n "$DEBUG" ]; then
   TYPE="Debug"
 fi
 
+
+
+DEB_DIR=`readlink -m ${DEB_DIR}`
 echo "*******************************"
-echo " Name: ${NAME}"
-echo " Ver:  ${VER}"
-[ "${TYPE}" = "-b"    ] && echo " Type: binary"
-[ "${TYPE}" = "-S"    ] && echo " Type: source"
-[ "${TYPE}" = "Debug" ] && echo " Type: debug"
+echo " Tar file:   ${TAR_FILE}"
+echo " Debian dir: ${DEB_DIR}"
+echo ""
+echo " Name:    ${PROGRAM}"
+echo " Ver:     ${VERSION}"
+echo " Type:    ${TYPE}"
 echo " Distrib: ${DISTRIB}"
-echo " Release: ${RELEASE}"
-echo " Source:  ${SRC}"
+echo " Release: ${RELEASES}"
 echo " Out dir: ${OUT_DIR}"
-[ -n "${DEB_DIR}" ] && echo " Debian dir: ${DEB_DIR}"
+
 echo "*******************************"
 
 
 OUT_DIR=`readlink -m ${OUT_DIR}`
 mkdir -p ${OUT_DIR} || exit 2
 
-DIR=${OUT_DIR}/${NAME}-${VER}
+DIR=${OUT_DIR}/${PROGRAM}-${VERSION}
 rm -rf ${DIR}
 
-if [ -z "${DEB_DIR}" ]; then
-    DEB_DIR=${DIR}/distr/deb/debian
-fi
 
-if [ -z "$DEBUG" ]; then
-    if [ ${SRC_TYPE} = "DIR" ]; then
-        cp -r ${SRC} ${DIR}
-        rm -rf ${DIR}/.git \
-               ${DIR}/build
+ORIG_TAR=${OUT_DIR}/${PROGRAM}_${VERSION}.orig.tar.gz
 
-        cd ${DIR}/.. && tar cjf ${NAME}_${VER}.orig.tar.bz2 ${NAME}-${VER}
+cp "${TAR_FILE}" ${ORIG_TAR} || error
 
-    else
-        cp "${SRC}" ${OUT_DIR}/${NAME}_${VER}.orig.tar.bz2
-        cd ${OUT_DIR} && tar xvf ${NAME}_${VER}.orig.tar.bz2 ${NAME}-${VER}
+eval $(gpg-agent --daemon)
 
-    fi
-fi
+for RELEASE in ${RELEASES}; do
+    printf "${COLOR_BLUE}  %-50s${COLOR_NORM}\n" "${DISTRIB} - ${RELEASE}"
 
-
-for RELEASE in ${RELEASE}; do
     # Debin directory .....................
-    rm -r ${DIR}/debian 2>/dev/null
+    [ -d ${DIR} ] && rm -r ${DIR}
+    mkdir -p ${DIR}
+
+    if [ -z "$DEBUG" ]; then
+        tar xf ${ORIG_TAR} --directory="${DIR}" --strip 1 || error
+    fi
+
     mkdir -p ${DIR}/debian
-    mkdir -p ${DIR}/debian/source
     DATE=`date -R`
 
     clearVariables
+
     prepareFile ${DEB_DIR}/control > ${DIR}/debian/control
 
     for src in `find ${DEB_DIR} -type f \! -name "control"`; do
         dest=$(echo $src | sed -e"s|${DEB_DIR}|${DIR}/debian|")
+        mkdir -p $(dirname "${dest}")
         prepareFile "${src}" > ${dest}
         chmod --reference "${src}" ${dest}
     done
     # Debin directory .....................
 
+    # Apply patches .......................
+    if [ -f "${DIR}/debian/patches/series" ]; then
+    	export QUILT_PATCHES=debian/patches
+    	cd ${DIR} && quilt push -a || exit 2
+    	[ -d "${DIR}" ] && rm -rf ${DIR}/.pc
+	fi    	
+    # Apply patches .......................
+
+
     if [ -z "$DEBUG" ]; then
-      cd ${DIR} && debuild ${TYPE} ${SIGN} -rfakeroot
+      cd ${DIR} && debuild ${type_arg} ${sign_arg} -rfakeroot
       ret=$?
       [ $ret -eq 0 ] || exit $ret
     else
@@ -398,7 +384,8 @@ for RELEASE in ${RELEASE}; do
     fi
 done
 
-if [ "${TYPE}" = '-b' ]; then
+
+if [ "${type_arg}" = '-b' ]; then
     echo "................................."
     echo "Check files:"
     PKGS=`awk '/Package:/ {print $2}' ${DIR}/debian/control`
@@ -425,4 +412,9 @@ if [ "${TYPE}" = '-b' ]; then
 
     done
 fi
+
+if [[ ${PPA} != "" ]]; then
+    echo "dput ppa:${PPA} *_source.changes" > ${OUT_DIR}/send.sh
+    chmod a+x ${OUT_DIR}/send.sh
+fi    
 
